/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2022-12-24 12:05:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch13;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ch13.board.BoardDBBean;
import ch13.board.BoardDataBean;
import java.text.SimpleDateFormat;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/ch13/js/color.jspf", Long.valueOf(1671805207000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ch13.board.BoardDBBean");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("ch13.board.BoardDataBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

   String bodyback_c="#FFF0B5";
   String value_c="#FFE271";

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>게시판</title>\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("<body bgcolor=\"");
      out.print(bodyback_c);
      out.write('"');
      out.write('>');
      out.write('\n');

	int num = Integer.parseInt(request.getParameter("num"));
	String pageNum = request.getParameter("pageNum");
	
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
	try{
		BoardDBBean dbPro = BoardDBBean.getInstance();
		BoardDataBean article = dbPro.getArticle(num);
		int ref = article.getRef();
		int re_step = article.getRe_step();
		int re_level = article.getRe_level();

      out.write("\n");
      out.write("	<p> 글 내용 보기</p>\n");
      out.write("	<form>\n");
      out.write("		<table>\n");
      out.write("			<tr height=\"30\">\n");
      out.write("				<td align=\"center\" width=\"125\" align=\"center\" bgcolor=\"");
      out.print(value_c);
      out.write("\">글번호</td>\n");
      out.write("				<td align=\"center\" width=\"125\" align=\"center\">");
      out.print(article.getNum() );
      out.write("</td>\n");
      out.write("				<td align=\"center\" width=\"125\" align=\"center\" bgcolor=\"");
      out.print(value_c);
      out.write("\">조회수</td>\n");
      out.write("				<td align=\"center\" width=\"125\" align=\"center\">");
      out.print(article.getReadcount() );
      out.write("</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr height=\"30\">\n");
      out.write("				<td align=\"center\" width=\"125\" align=\"center\" bgcolor=\"");
      out.print(value_c);
      out.write("\">작성자</td>\n");
      out.write("				<td align=\"center\" width=\"125\" align=\"center\">");
      out.print(article.getWriter() );
      out.write("</td>\n");
      out.write("				<td align=\"center\" width=\"125\" align=\"center\" bgcolor=\"");
      out.print(value_c);
      out.write("\">작성일</td>\n");
      out.write("				<td align=\"center\" width=\"125\" align=\"center\">");
      out.print(sdf.format(article.getReg_date()) );
      out.write("</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr height=\"30\">\n");
      out.write("				<td align=\"center\" width=\"125\" align=\"center\" bgcolor=\"");
      out.print(value_c);
      out.write("\">글제목</td>\n");
      out.write("				<td align=\"center\" width=\"125\" align=\"center\" colspan=\"3\">");
      out.print(article.getSubject() );
      out.write("</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr height=\"30\">\n");
      out.write("				<td align=\"center\" width=\"125\" align=\"center\" bgcolor=\"");
      out.print(value_c);
      out.write("\">글내용</td>\n");
      out.write("				<td align=\"center\" width=\"125\" align=\"center\" colspan=\"3\">\n");
      out.write("				<pre>");
      out.print(article.getContent());
      out.write("</pre></td>	\n");
      out.write("			</tr>\n");
      out.write("			<tr height=\"30\">\n");
      out.write("				<td colspan=\"4\" bgcolor =\"");
      out.print(value_c );
      out.write("\" align=\"right\">\n");
      out.write("					<input type=\"button\" value=\"글수정\" \n");
      out.write("					onclick=\"document.location.href='updateForm.jsp?num=");
      out.print(article.getNum());
      out.write("&pageNum=");
      out.print(pageNum);
      out.write("'\">\n");
      out.write("					&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("					<input type=\"button\" value=\"글삭제\" \n");
      out.write("					onclick=\"document.location.href='deleteForm.jsp?num=");
      out.print(article.getNum());
      out.write("&pageNum=");
      out.print(pageNum);
      out.write("'\">\n");
      out.write("					&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("					<input type=\"button\" value=\"댓글쓰기\" \n");
      out.write("					onclick=\"document.location.href='writeForm.jsp?num=");
      out.print(num);
      out.write("&ref=");
      out.print(ref);
      out.write("&re_step=");
      out.print(re_step);
      out.write("&re_level=");
      out.print(re_level);
      out.write("'\">\n");
      out.write("					&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("					<input type=\"button\" value=\"글목록\"\n");
      out.write("					onclick=\"document.location.href='list.jsp?num=");
      out.print(pageNum);
      out.write("'\">\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("		");

		}catch(Exception e){}
		
      out.write("\n");
      out.write("	</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
