/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2022-12-27 04:09:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch14shop.manager.logon;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class managerLoginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>로그인</title>\n");
      out.write("<link href=\"../../etc/login.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"title-login\">\n");
      out.write("		<h2>로그인 폼</h2>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"login-wrap\">\n");
      out.write("		<div class=\"login-html\">\n");
      out.write("			<input id=\"tab-1\" type=\"radio\" name=\"tab\" class=\"sign-in\" checked>\n");
      out.write("			<label for=\"tab-1\" class=\"tab\">Sign In</label> <input id=\"tab-2\"\n");
      out.write("				type=\"radio\" name=\"tab\" class=\"sign-up\"> <label for=\"tab-2\"\n");
      out.write("				class=\"tab\">Sign Up</label>\n");
      out.write("			<div class=\"login-form\">\n");
      out.write("				<!-- 로그인 기능  -->\n");
      out.write("				<div class=\"sign-in-htm\">\n");
      out.write("					<form method=\"post\" action=\"managerLoginPro.jsp\">\n");
      out.write("						<div class=\"group\">\n");
      out.write("							<label for=\"user\" class=\"label\">Username</label> <input id=\"user\"\n");
      out.write("								type=\"text\" class=\"input\" name=\"id\" maxlength=\"50\"\n");
      out.write("								style=\"ime-mode: inactive;\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"group\">\n");
      out.write("							<label for=\"pass\" class=\"label\">Password</label> <input id=\"pass\"\n");
      out.write("								class=\"input\" type=\"password\" data-type=\"password\" name=\"passwd\"\n");
      out.write("								maxlength=\"16\" style=\"ime-mode: inactive;\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"group\">\n");
      out.write("							<input id=\"check\" type=\"checkbox\" class=\"check\" checked>\n");
      out.write("							<label for=\"check\"> <span class=\"icon\"></span>Keep me\n");
      out.write("								Signed in\n");
      out.write("							</label>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"group\">\n");
      out.write("							<input type=\"submit\" class=\"button\" value=\"Sign In\">\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("					<div class=\"hr\"></div>\n");
      out.write("					<div class=\"foot-lnk\">\n");
      out.write("						<a href=\"#forgot\">Forgot Password?</a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"sign-up-htm\">\n");
      out.write("					<div class=\"group\">\n");
      out.write("						<label for=\"user\" class=\"label\">Username</label> <input id=\"user\"\n");
      out.write("							type=\"text\" class=\"input\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"group\">\n");
      out.write("						<label for=\"pass\" class=\"label\">Password</label> <input id=\"pass\"\n");
      out.write("							type=\"password\" class=\"input\" data-type=\"password\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"group\">\n");
      out.write("						<label for=\"pass\" class=\"label\">Repeat Password</label> <input\n");
      out.write("							id=\"pass\" type=\"password\" class=\"input\" data-type=\"password\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"group\">\n");
      out.write("						<label for=\"pass\" class=\"label\">Email Address</label> <input\n");
      out.write("							id=\"pass\" type=\"text\" class=\"input\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"group\">\n");
      out.write("						<input type=\"submit\" class=\"button\" value=\"Sign Up\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"hr\"></div>\n");
      out.write("					<div class=\"foot-lnk\">\n");
      out.write("						<label for=\"tab-1\">Already Member?</label>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
