/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2022-12-27 02:28:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch14shop.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class managerMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/ch14shop/manager/../etc/color.jspf", Long.valueOf(1672048062000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
 
  String bodyback_c="#e0ffff";
  String back_c="#8fbc8f";
  String title_c="#5f9ea0";
  String value_c="#b0e0e6";
  String bar="#778899";

      out.write('\n');

String managerId = "";
try {
	// 로그인 정보를 받아와 세션 유지를 가능 하게 해줌
	// 관리자 ID 정보를 확인함. 틀리면 해당 페이지를 볼수가 없다.
	managerId = (String) session.getAttribute("managerId");
	if (managerId == null || managerId.equals("")) {
		response.sendRedirect("logon/managerLoginForm.jsp");
	} else {

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>책관리</title>\n");
      out.write("<link href=\"../etc/login.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"title-login\">\n");
      out.write("		<h2>로그인 화면</h2>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"login-wrap\">\n");
      out.write("		<div class=\"login-html\">\n");
      out.write("			<input id=\"tab-1\" type=\"radio\" name=\"tab\" class=\"sign-in\" checked>\n");
      out.write("			<label for=\"tab-1\" class=\"tab\">");
      out.print(managerId);
      out.write(" 접속</label>\n");
      out.write("			<div class=\"login-form\">\n");
      out.write("				<!-- 매니저 로그인 세션 창이 나온다. -->\n");
      out.write("				<table>\n");
      out.write("					<tr>\n");
      out.write("						<td align=\"center\" bgcolor=\"");
      out.print(bar);
      out.write("\">상품관련 작업</td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td><a href='productProcess/bookRegisterForm.jsp'>상품등록</a></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td><a href='productProcess/bookList.jsp?book_kind=all'>상품수정/삭제</a></td>\n");
      out.write("					</tr>\n");
      out.write("				</table>\n");
      out.write("				<br> <br>\n");
      out.write("				<table>\n");
      out.write("					<tr>\n");
      out.write("						<td align=\"center\" bgcolor=\"");
      out.print(bar);
      out.write("\">구매된 상품관련 작업</td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td><a href='orderedProduct/orderedList.jsp'>전체 구매목록 확인</a></td>\n");
      out.write("					</tr>\n");
      out.write("				</table>\n");
      out.write("				<br> <br>\n");
      out.write("				<form method=\"post\" action=\"logon/managerLogout.jsp\">\n");
      out.write("					<div class=\"group\">\n");
      out.write("						<b>관리 작업중...</b> <br> <br> \n");
      out.write("						<input type=\"submit\" class=\"button\" value=\"로그아웃\">\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");

}
} catch (Exception e) {
e.printStackTrace();
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
